const CONFIG = {

  APP_NAME: "BadPlanner",

  APP_VERSION: "0.16.0",

  SPREADSHEET_ID:
    PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID"),

USAGE_METRICS_SPREADSHEET_ID:
	PropertiesService.getScriptProperties().getProperty("USAGE_METRICS_SPREADSHEET_ID"),

  SHEET_NAME: "Master",
  PARAMETERS_SHEET_NAME: "Parameters",
  LOCATIONS_SHEET_NAME: "Locations",
  DEPARTMENTS_SHEET_NAME: "Departments",
  USAGE_METRICS_SHEET_NAME: "Logs",
    
  LOCALE: "fr-FR",

  STATUS: {
	  EVENT: {
		UPCOMING: "UPCOMING",
		ONGOING: "ONGOING",
		FINISHED: "FINISHED"
	  },
	  REGISTRATION: {
		UNKNOWN: "UNKNOWN",
		NOT_OPEN: "NOT_OPEN",
		OPEN: "OPEN",
		CLOSED: "CLOSED"
	  }
  }
};

const USAGE_METRICS = {

  APP_OPEN: "APP_OPEN",

  APP_LOAD_SUCCESS: "APP_LOAD_SUCCESS",
  APP_LOAD_FAILED: "APP_LOAD_FAILED",
  APP_LOAD_DURATION: "APP_LOAD_DURATION",

  FILTER_CATEGORY: "FILTER_CATEGORY",
  FILTER_TYPE: "FILTER_TYPE",
  FILTER_SCOPE: "FILTER_SCOPE",
  FILTER_FINISHED_TOURNAMENT: "FILTER_FINISHED_TOURNAMENT",
  FILTER_NEW_TOURNAMENT: "FILTER_NEW_TOURNAMENT",

  FILTER_RESET: "FILTER_RESET",

  CARD_EXPAND: "CARD_EXPAND",

  BADNET_OPEN: "BADNET_OPEN",
  MAPS_OPEN: "MAPS_OPEN",
  CALENDAR_EXPORT: "CALENDAR_EXPORT"

};